version: '3.7'

services:
  api:
    build:
      context: .
    container_name: api
    depends_on:
      - mongo
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - ./app.js:/srv/app.js

  mongo:
    image: mongo:4.1.4-xenial
    container_name: mongoDB
    restart: always
    networks:
      - internal
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: crud-mong

networks:
  internal:
    driver: bridge

volumes:
  mongo_data: